/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomButtonGroup: typeof import('./src/components/custom-button-group/custom-button-group.vue')['default']
    CustomFixed: typeof import('./src/components/custom-fixed/custom-fixed.vue')['default']
    CustomNavBar: typeof import('./src/components/custom-nav-bar/index.vue')['default']
    CustomShoppingCart: typeof import('./src/components/custom-shopping-cart/custom-shopping-cart.vue')['default']
    CustomStep: typeof import('./src/components/custom-step/custom-step.vue')['default']
    CustomTabbar: typeof import('./src/components/custom-tabbar/custom-tabbar.vue')['default']
    CustomTitle: typeof import('./src/components/custom-title/custom-title.vue')['default']
    CustomTuan: typeof import('./src/components/custom-tuan/custom-tuan.vue')['default']
    GoodPicker: typeof import('./src/components/good-picker/components/good-picker.vue')['default']
    LayoutComp: typeof import('./src/components/layout-comp.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    PopupLogin: typeof import('./src/components/popup-login.vue')['default']
    PopupTuan: typeof import('./src/components/popup-tuan/popup-tuan.vue')['default']
    Poster: typeof import('./src/components/poster.vue')['default']
    Qrcode: typeof import('./src/components/qrcode.vue')['default']
    UvUiTools: typeof import('./src/components/uv-ui-tools/uv-ui-tools.vue')['default']
    UvWaterfall: typeof import('./src/components/uv-waterfall/components/uv-waterfall/uv-waterfall.vue')['default']
  }
}
